---
- name: Remove existing Loki plugin if any
  community.docker.docker_plugin:
    plugin_name: loki
    state: absent
    force_remove: true
  ignore_errors: true

- name: Install Loki plugin disabled (amd64)
  ansible.builtin.command: >
    docker plugin install grafana/loki-docker-driver:3.3.2-amd64 --alias loki --grant-all-permissions --disable

- name: Wait for Loki plugin to appear in plugin list
  retries: 6
  delay: 5
  ansible.builtin.shell: docker plugin ls | grep loki
  register: loki_plugin
  until: loki_plugin.rc == 0
  ignore_errors: true

- name: Enable Loki plugin
  community.docker.docker_plugin:
    plugin_name: loki
    state: enable

- name: Verify Loki plugin is enabled
  ansible.builtin.command: docker plugin ls
  register: plugin_list

- debug:
    var: plugin_list.stdout

- name: Create Docker Compose directory
  file:
    path: "{{ docker_compose_dir }}"
    state: directory
    mode: '0755'

- name: Template Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/docker-compose.yml
    force: yes

- name: Run Docker Compose up
  command: docker compose -f {{ docker_compose_dir }}/docker-compose.yml up -d
  args:
    chdir: "{{ docker_compose_dir }}"
